In [2]:
import numpy as np

In [3]:
arreglo_0_a_90_grados = np.array([0,30,45,60,90])


array([ 0, 30, 45, 60, 90])

In [4]:
radianes = arreglo_0_a_90_grados * np.pi / 180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [7]:
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [33]:
arreglo_random = np.random.randint(10)#enteros + hasta el numero puesto
arreglo_random #[0,10[

5

In [57]:
arreglo_random = np.random.randint(-1,2)#enteros + hasta el numero puesto
arreglo_random #[-1,2[

0

In [61]:
arreglo_random = np.random.randint(0,11,3)#minimo, maximo, numero de randomicos
arreglo_random #[0,11[

array([5, 4, 4])

In [62]:
arreglo_random.mean()

4.333333333333333

In [63]:
np.median(arreglo_random)

4.0

In [64]:
np.std(arreglo_random)

0.4714045207910317

In [65]:
np.var(arreglo_random)

0.22222222222222224

In [66]:
np.mean(arreglo_random)

4.333333333333333